### ISSUE TITLE
"Render Selected Keyframes" not working in Blender 5.0

### ISSUE THREAD

**Issue by jspinn** [p2or/blender-loom#124]
Hi Christian,

Seems like the updated Blender 5.0 API broke the `Render Selected Keyframes` functionality with the [removal of the legacy Action API](https://projects.blender.org/blender/blender/commit/1395abc502ec2801b243c50f0ee4f83a392f3937). Do you have any plans to update this function to be compatible with 5.0?

I referenced these to take a quick stab at updating it for compatibility, but I'm not familiar with Blender's API, so my quick attempts were not successful!

https://blenderartists.org/t/how-to-access-fcurves-in-blender-5-0/1623022
https://developer.blender.org/docs/release_notes/5.0/python_api/

```
Python: Traceback (most recent call last):
  File "C:\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\loom.py", line 1547, in invoke
    return self.execute(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\loom.py", line 1576, in execute
    selected_keys = self.keyframes_from_actions(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AppData\Roaming\Blender Foundation\Blender\5.0\scripts\addons\loom.py", line 1485, in keyframes_from_actions
    for channel in action.fcurves: #if channel.select:
                   ^^^^^^^^^^^^^^
AttributeError: 'Action' object has no attribute 'fcurves'
```

Thanks for your hard work on this add-on!

**Comment by p2or** [comment]
Hi @jspinn,

thank you very much for your report and for taking the time to investigate. I didn't notice this issue because I don't use 'Render Selected Keyframes' on a regular basis. However, with the [latest commit](https://github.com/p2or/blender-loom/commit/06f816f50ae9e51ab45f44ff06b3704e8f2b1e31), I believe we are back to normal now. 

If you have time, please download the [latest version](https://github.com/p2or/blender-loom/archive/refs/heads/master.zip) from the master branch and report back. Thank you.

Cheers,
Christian

**Comment by jspinn** [comment]
Works perfectly now in 5.0. Thanks so much for the quick update!
