### ISSUE TITLE
Loom is my hero, but since my dreaded Win 11 upgrade it is not working in Blender 4.4.1 ?

### ISSUE THREAD

**Issue by protovu** [p2or/blender-loom#125]
Hello Christian!

What happens is:  Loom opens, then immediately disappears when I try to launch a render.

When I try the batch render, I get this:
Octane Ocio Management Update End. Time cost: 0.00 secs
Clear Octane Resource Cache System
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\loom.py", line 3987, in execute
    if scn.render.use_sequencer and len(scn.sequence_editor.sequences):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sequences'
Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\loom.py", line 3987, in execute
    if scn.render.use_sequencer and len(scn.sequence_editor.sequences):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sequences'
Location: C:\Program Files\BlenderOctane4.4.1\blendoct30\OctaneBlender30.3.0\4.4\scripts\modules\bpy\ops.py:109
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\BlenderOctane4.4.1\blendoct30\OctaneBlender30.3.0\4.4\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.4\scripts\addons\loom.py", line 3987, in execute
    if scn.render.use_sequencer and len(scn.sequence_editor.sequences):
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sequences'
Location: C:\Program Files\BlenderOctane4.4.1\blendoct30\OctaneBlender30.3.0\4.4\scripts\modules\bpy\ops.py:109

Clear Octane Resource Cache System

Blender quit
Press any key to continue . . .

Chat has sent me down a rabbit hole well above my paygrade (just wanted you to know I tried not to bug you).

Is there anything we can do?  I need to use 4.4.1 because it is stable with Octane Render (in which I have a massive body of work).

Thank you for looking,
Rick

**Comment by p2or** [comment]
Hi @protovu,

thanks for your report. I guess you are using an old version of Loom, as the line that is causing the error:

```py
if scn.render.use_sequencer and len(scn.sequence_editor.sequences):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
is no longer part of the actual code (https://github.com/p2or/blender-loom/commit/1b9be4ac2cffa65de389bdec5b1de60630100ef4). Could you please update Loom and report back? Filed a [new release](https://github.com/p2or/blender-loom/releases/tag/0.9.5) four weeks ago that is compatible with Blender versions above 4.2+. Does that help?

Cheers,
Christian

**Comment by protovu** [comment]
You are absolutely right. I just got it working! In using both Blender 3.3 and 4.4 I had created a problem for myself. By changing the location of the newer file and being certain to add it correctly, I am now seeing the hoped for behavior. Thank you again for this great addon. It should be part of Blender proper.
Rick

**Comment by p2or** [comment]
You're welcome @protovu. Glad it's working! Cheers, Christian
